### ISSUE TITLE
Map Page - Pin Colors

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#28]
All pins are always red.

**Comment by fbrooks1056** [comment]
Fritz to talk to V about creating color icons.

**Comment by phillipskevin** [comment]
@kevindwyer are there specific requirements for the pin colors? Can you pick one of these options or let me know what the rules should be?

### option 1
red = no services are available?
green = at least one service is available?

### option 2
red = no services that the user searched for are available?
green = at least one service that the user searched for is available?

**Comment by viwinger** [comment]
I can work on creating icons. Can you elaborate on what the icons should look like? Do they need to be the same as what they are now only in different colors?

**Comment by kevindwyer** [comment]
@phillipskevin Option 2
@fbrooks1056 @viwinger we discussed this last weekend. Could you make sure I'm being consistent, please? 

User searches using only one filter Service X: 
If 'IsAvailable' for Service X is False; pin color = Red
If "IsAvailable' for Service X is True, and it is inside Hours for that service (not closed); pin color = Green
If "IsAvailable' for Service X is True, and it is outside Hours for that service; pin color = Yellow

User seaches for Service X and Service Y, and both have the same location/Organziation:
If either Service X or Service Y "IsAvaliable" = True, and that service is inside hours; pin color = Green. 
If either Service X or Service Y "IsAvaliable" = True, and that service is outside hours; pin color = Yellow
If both Service X and Service Y "IsAvailable" = False, pin color = Red

**Comment by kevindwyer** [comment]
@viwinger -Yep, same basic markers, just three colors (Green, Yellow, Red)

**Comment by phillipskevin** [comment]
This was fixed by https://github.com/HealthConnectLink/HCL-FRONTEND/pull/30.
