### ISSUE TITLE
Handle empty search location

### ISSUE THREAD

**Issue by phillipskevin** [HealthConnectLink/HCL-FRONTEND#41]
From https://github.com/HealthConnectLink/HCL-FRONTEND/issues/38.

Refer to https://github.com/HealthConnectLink/HCL-FRONTEND/wiki/Results-Page-Logic.
- [ ] If search location is blank and no filters are selected results page should center on users (IP) location and return all possible Orgs in that map window
- [ ] If search location is blank and at least 1 filter is selected results page should center on users (IP) location

**Comment by kevindwyer** [comment]
I figured out how to make gifs! Woo :dancing_men: 

http://g.recordit.co/HvYRP60zcG.gif
