### ISSUE TITLE
Pin Color vs Service_Org Font Color

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#49]
There are never any yellow pins. What's up with that? 
Is the pin color logic active?
Also, the font color for service_org in the accordion menu are all green. 
Organization names on the org page seem to be red and green randomly. This may be an artifact of some hard coding or other old logic
 
Ref wiki for pin/service_org color logic
https://github.com/HealthConnectLink/HCL-FRONTEND/wiki/Pin-Color-Org-Page-Service-Font-Color-Logic

**Comment by phillipskevin** [comment]
It's very possible that it's wrong, but the logic is in place on the front end. Can you give an example URL for a search results page and organization page that is showing unexpected pin colors, @kevindwyer? I can take a look at the service data and double check the logic.

One thing to note is that right now it's not checking if it is within the service hours, so maybe that is the problem.

**Comment by kevindwyer** [comment]
Community Action Coalition has a red pin on the map when we search for 'At risk/homeless housing support and assistance' 

![screen shot 2017-03-11 at 5 47 32 pm](https://cloud.githubusercontent.com/assets/23562482/23827834/059ae580-0683-11e7-93c8-f306f99db230.png)

On the org page the Org Name is in red font for some reason (this should be black), and none of the service names in the accordion menu are red (to match the pin color on the map page)

![screen shot 2017-03-11 at 5 47 25 pm](https://cloud.githubusercontent.com/assets/23562482/23827841/2b87486a-0683-11e7-911e-712b61ccf336.png)

So far I haven't seen any red service names on any org pages :/

**Comment by phillipskevin** [comment]
Ok, that was just confusion by me. I didn't color the service names, just the organization name. I'll make that change.

**Comment by kevindwyer** [comment]
Cool, thanks. When I saw the org names had changed colors I assumed you were just testing the logic out. With this or anything else we can always slack call or talk on the phone

**Comment by phillipskevin** [comment]
Closed by #61.
