### ISSUE TITLE
Create Organization Page

### ISSUE THREAD

**Issue by phillipskevin** [HealthConnectLink/HCL-FRONTEND#5]
- [x] app should have an organization page at `/organization/{id}`
- [x] page should retrieve organization details from `/api/organization/{id}`
- [x] organization page should show details about the organization
- [x] organization page should look like this mockup: [organization.pdf](https://github.com/HealthConnectLink/HCL-FRONTEND/files/709465/organization.pdf)

**Comment by djlitvak** [comment]
Can we change the word "profile" to "organization"? In the future, we plan to include user profiles and such. I'd like to try to save that word.

**Comment by phillipskevin** [comment]
@djlitvak sounds good

**Comment by viwinger** [comment]
Is there anything left to be done on this page?

**Comment by phillipskevin** [comment]
I think just https://github.com/HealthConnectLink/HCL-FRONTEND/issues/26, so this one can be closed.
