### ISSUE TITLE
Search Page Small Quick Menu Button - Large Quick Menu Button

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#51]
After making a selection from the quick menu and completing a search, I notice that the size/shape of the quick menu button changes whenever you return to the search page. 
![screen shot 2017-03-11 at 5 20 05 pm](https://cloud.githubusercontent.com/assets/23562482/23827738/323a1a96-0680-11e7-979a-74d0dacbab72.png)
![screen shot 2017-03-11 at 5 22 57 pm](https://cloud.githubusercontent.com/assets/23562482/23827739/3829ed50-0680-11e7-80e7-e6e1020ad8eb.png)

**Comment by viwinger** [comment]
@phillipskevin does this have to do with those css issues that we were having where they wouldn't update on the results page?

**Comment by phillipskevin** [comment]
Yeah. I'll take care of this.
