### ISSUE TITLE
Scrolling in the Quick Menu 

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#52]
The quick menu (dropdown) on the search page and the map page is not long enough for 10 search terms. 

Scrolling in the quick menu is not ideal. Would it be possible to resize the quick menu dropdown and/or should we reduce the number of terms?

**Comment by kevindwyer** [comment]
Thank you. on my screen the very bottom edge of the quick menu is cut off. This makes it hard to tell if you are seeing every option in the menu. Suggested fixes?

**Comment by phillipskevin** [comment]
We'll revisit this after @viwinger's changes are in.
