### ISSUE TITLE
Map Page Buttons - HTML/CSS issue

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#54]
The location search box, quick menu button, and print button have lost their style. 
![screen shot 2017-03-11 at 5 24 33 pm](https://cloud.githubusercontent.com/assets/23562482/23827798/052170ac-0682-11e7-9626-ab5107839c8a.png)

**Comment by phillipskevin** [comment]
@viwinger can you take a look at this?

**Comment by viwinger** [comment]
@kevindwyer what do you want it to look like?

**Comment by kevindwyer** [comment]
@viwinger 
![image](https://cloud.githubusercontent.com/assets/23562482/23915137/297954a2-08b6-11e7-90e4-0db4079413b3.png)

**Comment by viwinger** [comment]
I'm sorry if I am way out of the loop but @phillipskevin did this ever get figured out why the multi-select wasn't responding to the CSS changes?

**Comment by phillipskevin** [comment]
I did figure it out and tried to explain here: https://github.com/HealthConnectLink/HCL-FRONTEND/issues/46#issuecomment-285865974

The basics are that all styles for the services dropdown are 

- now in the one css file: https://github.com/HealthConnectLink/HCL-FRONTEND/blob/master/src/app/services-multiselect/services-multiselect.component.css

- you need to put `/deep/` before any styles for elements inside of the `<ss-multiselect-dropdown>`

- if you want to style the dropdown differently, add the `dropdownClass` attribute like I'm doing here: https://github.com/HealthConnectLink/HCL-FRONTEND/blob/master/src/app/results-page/results-page.html#L15 and then add styles based on that class

Sorry, this is now two long, confusing explanations to this.

**Comment by viwinger** [comment]
@phillipskevin Kind of forgot about naming convention for this...but I believe this should be fixed with my "mvp-1-fixes" Thanks @fbrooks1056 for reminding me of the naming convention.

**Comment by phillipskevin** [comment]
We're going to close this and come back to it after MVP 2 to clean up small style issues.
