### ISSUE TITLE
Map Pins - Action on Click

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#55]
Right now the map pins don't respond to a click. 
I believe users will expect something to happen when a pin is clicked. What do we think the appropriate response should be?

**Comment by phillipskevin** [comment]
I think it would make sense to link to the Organization page, but the user won't be able to easily tell which pin is for which result. Maybe we highlight the search results on the right as you hover over the pins? And then link to the Organization page for that result when you click on the pin.

**Comment by kevindwyer** [comment]
I think that is a great solution! I tagged this as an MVP 2 issue but I'll trust you to implement the changes whenever you feel like it makes sense
