### ISSUE TITLE
Org Page - Hours of Operation (all have hours:min:sec)

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#56]
On the org page in both the general contact info (on the left hand side of the screen) and under the service_org in the accordion menu, seconds are included in the org-hours and service_org hours. 

*EDIT* also, the hours are displayed in military time. This is consistent with what is in the DB and per @djlitvak request. But it needs to be converted to AM/PM for UX reasons. 

I think just having hours and minutes will be ok :)

**Comment by phillipskevin** [comment]
@fbrooks1056 you probably want to use a [Pipe](https://angular.io/docs/ts/latest/guide/pipes.html) for this. You can use the [angular-cli](https://github.com/angular/angular-cli) to generate one by running
```
npm run ng generate pipe time
```

This will allow you to use `| time` in your template like 

```
{{organization.hours_list[6].openTime | time}}
```

You can then put the logic for the `time` function in the generated `src/app/time.pipe.ts` file.

I know this is a lot. We can connect on screenhero some time to walk through it if you want.
