### ISSUE TITLE
Org Page - Org Names and Descriptions

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#57]
Some of the Org Names and descriptions are not showing up on Org_Pages

http://app.healthconnect.link.s3-website.us-east-2.amazonaws.com/organization/aad0f216-81ac-4d08-87eb-e9d9ad0256ec?serviceCodes=BH-0500

Is one example

**Comment by phillipskevin** [comment]
It looks like there is an error on this page, @fbrooks1056 can you take a look?

![image](https://cloud.githubusercontent.com/assets/5851984/23828430/d018a492-0696-11e7-8c3a-b57b5c60bfbb.png)

**Comment by phillipskevin** [comment]
Closed by #68.

**Comment by kevindwyer** [comment]
This looks to be working well. Nice job!
