### ISSUE TITLE
Service name doesn't always match serviceCode

### ISSUE THREAD

**Issue by phillipskevin** [HealthConnectLink/HCL-FRONTEND#60]
While investigating 

>There are never any yellow pins. What's up with that?

for https://github.com/HealthConnectLink/HCL-FRONTEND/issues/49, I found that `organizationService_list[x].name` does not always match `organizationService_list[x].service.serviceCode`. You can see an example below from http://hclapi-dev.us-east-2.elasticbeanstalk.com/search?serviceCode=BH-0500&serviceCode=BM-6500.1500&latitude=43.0730517&longitude=-89.40123019999999:

![image](https://cloud.githubusercontent.com/assets/5851984/23834413/16da6856-0724-11e7-9c9e-d818222062ef.png)

I'll update the front end code to use the `serviceCode`, but we still might want to fix this in the service. cc @fbrooks1056 @djlitvak

**Comment by djlitvak** [comment]
@phillipskevin The name of the service shouldn't be listed with BH-3800. That name is really for a brand name. An example is if an organization offers 3 different servies (clothing, housing, and food pantry). Then the `organizationService.name` would be "Klothes4Kids, Safe Warm Stay, and Food4All".

When you guys do a search, we are searching on the `service.serviceCode` field, not the `organizationService.name`

Does that make sense?

**Comment by phillipskevin** [comment]
Yep, that makes sense. I originally just assumed the `name` field was what I was looking for since it matched for some of them. I already updated the front end to use the `serviceCode` field. I'll go ahead and close this; feel free to re-open if you want to use it to track setting the `name`s to more brand name-y values.
