### ISSUE TITLE
Org Page - Accordion Menu information and layout

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#70]
The information displayed in the accordion menu needs some attention. This is the current display

![image](https://cloud.githubusercontent.com/assets/23562482/24152169/df87564c-0e18-11e7-9218-052563ef4590.png)

The layout should be more like this
![image](https://cloud.githubusercontent.com/assets/23562482/24152306/3ed9a4c4-0e19-11e7-888b-2c19b6a1dcfa.png)

Information labels (Payment Type, Restriction Notes, Contact information, Main Service Phone, Hours, Monday, Tuesday, etc....) should be bold font. 

Thank you

**Comment by fbrooks1056** [comment]
@viwinger and I should plan to co-work on this probably on Saturday.
