### ISSUE TITLE
Org Page - General Information

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#72]
Would it be possible to have left hand justification (as opposed to centered) for the general information on the org pages?

**Comment by phillipskevin** [comment]
from our dev team meeting:

- put the phone numbers in a table so numbers are lined up and the names are lined up
- put the hours in a table so days of the week are lined up and hours are lined up
- left align address, email, website fields
- keep entire section centered within gray box

**Comment by phillipskevin** [comment]
Still need to remove `( )` from around phone numbers

**Comment by fbrooks1056** [comment]
Just finished this up

**Comment by phillipskevin** [comment]
@fbrooks1056 finished this up.
