### ISSUE TITLE
If you select a location with no services, the page shouldn't break

### ISSUE THREAD

**Issue by phillipskevin** [HealthConnectLink/HCL-FRONTEND#74]

**Comment by kevindwyer** [comment]
I'm experiencing a weird bug with this feature:
If on the Search page you enter location "Madison, WI" and select Search the resulting Map Page has no pins and the Map Page drop down indicates "1 checked'. Not the expected response

If on the Search page you select a service from the drop down, click outside the drop down, then unselect the service from the drop down, then enter a location, then select search, the Map page will have every organization shown. The expected response. 

Strange......

**Comment by phillipskevin** [comment]
@kevindwyer you mean you search without selecting any services? You shouldn't be able to do that.

Maybe you can install https://licecap.en.softonic.com/download and post a gif of you doing this?

**Comment by kevindwyer** [comment]
Yes, search without selecting any services and you get this page
![image](https://cloud.githubusercontent.com/assets/23562482/24656799/7e22f180-1909-11e7-8726-ec41b4227745.png)

Will try to install that software and capture a gif tonight.

**Comment by phillipskevin** [comment]
Right, but how do you search? You shouldn't be able to click the button without selecting a service.

![no-searchy](https://cloud.githubusercontent.com/assets/5851984/24656903/4a5d2e98-1912-11e7-92e9-318d5f543425.gif)
