### ISSUE TITLE
Dropdown Fixes/Update 

### ISSUE THREAD

**Issue by viwinger** [HealthConnectLink/HCL-FRONTEND#87]
I am going to work on fixing this some more this week

**Comment by phillipskevin** [comment]
One remaining issue is to make the font the same when the button is disabled.

Also, font case should be consistent. Either all caps or all first-letter capitalized.

Here are the options for the services dropdown: https://github.com/softsimon/angular-2-dropdown-multiselect

They can be set here: https://github.com/HealthConnectLink/HCL-FRONTEND/blob/master/src/app/services-multiselect/services-multiselect.component.ts#L40-L60
