### ISSUE TITLE
Search Page - Make Buttons Match

### ISSUE THREAD

**Issue by kevindwyer** [HealthConnectLink/HCL-FRONTEND#90]
Quick menu button does not match the Search button. They should be the same size/shape and have the same font and colors. 

![image](https://cloud.githubusercontent.com/assets/23562482/24615387/b7ea4460-1853-11e7-8910-538422187eac.png)

**Comment by viwinger** [comment]
Also fixed with ticket#53

**Comment by kevindwyer** [comment]
Is this ready to be deployed?
